### ISSUE TITLE
Question about timezone & organizer

### ISSUE THREAD

**Issue by chocolata** [itsnubix/nowcal#3]
Hi, 

I got here because of this mention on how to attach an ICS file to an email (exactly what I was looking for).
[https://github.com/spatie/calendar-links/issues/44#issuecomment-465194452](https://github.com/spatie/calendar-links/issues/44#issuecomment-465194452)

I implemented your solution and am loving how simple it is.
The only issue is that I'm having issues displaying the event start time in my timezone (CET).
For some reason it keeps reverting to CEST, which is completely off.

My event should start at 09:00, but it is constantly being shown as 11:00 (CEST)

Do you know how I can define the timezone in the generated ICS file?
Also, it would be good to be able to set the "organizer" field aswel...

This is the generated file:

```
BEGIN:VCALENDAR
PRODID:-//itsnubix//NowCal//EN
VERSION:2.0
BEGIN:VEVENT
UID:78bcbd60-44bd-45c7-898f-effc83536ad6
CREATED:20230214T144133Z
DTSTAMP:20230214T144133Z
DTSTART:20230606T090000Z
DTEND:20230606T190000Z
SUMMARY:My event name
LOCATION:My location, Address 1, 5000 City
END:VEVENT
END:VCALENDAR

```
I see some mentions of differently generated ICS files here:
[https://stackoverflow.com/questions/7626114/ics-timezone-not-working](https://stackoverflow.com/questions/7626114/ics-timezone-not-working)

Do you have any suggestions?

**Comment by kylemilloy** [comment]
In addition to the organizer there's a bunch of things you can set as per the RFC spec here: https://www.rfc-editor.org/rfc/rfc5545

Looking at this package it's quite strict on what it does and doesn't let you set and I could open that up a bit. 

In the meantime, to solve your issue what you can do is a bit of a workaround...

If you get the raw output...

```php
$output = NowCal::raw($props);
```

What you can then do is add your own key/val pairs before the `END:VCALENDAR`. So something like:

```php
$output = NowCal::raw($props);

array_splice($output, count($output) - 1, 0, 'ORGANIZER;SENT-BY="mailto:test@example.com');
```

Then from there you can convert it to a file like how this package does:

```php
$output = NowCal::raw($props);

array_splice($output, 3, 0, 'ORGANIZER;SENT-BY="mailto:test@example.com"');
$content = implode("\r\n", $output); // conform the structure of the ics file to make

$filename = tempnam(sys_get_temp_dir(), 'event_').'.ics'; // where to store it
file_put_contents($filename, $content); // write to the file

return $filename; // use this to point to the file in question.
```

Check the RFC for the exact spec you're supposed to use for ORGANIZER...I think it might have to be inside the `BEGIN:VEVENT` part to be valid so if that's the case you can inject it there instead of before the END:VCALENDAR. 

As for the timezone stuff your time is indeed in UTC (aka Zulu) which it is being forced into. I think you could either pass it a date via Carbon or DateTime that has the a CET or CEST timezone on it already which _should_ adjust the timezone for you...see this [stack](https://stackoverflow.com/questions/45870577/laravel-carbon-how-to-change-timezone-without-changing-the-hour) for details on how you might do that with Carbon..

Otherwise you can force a timezone on it using the method above to modify the raw values...look for the index of DTSTART and DTEND and modify the values therein by slicing off the Z and replacing it with the timezone identifier.

**Comment by chocolata** [comment]
Hi @kylemilloy,

Thanks for your extensive answer. I've been tinkering with it the whole day yesterday and as I'm getting a bit short of time, I went for the easy way... I just generated the ICS file via an external tool and uploaded it to my project, and included it that way in the email confirmation the people get. Now the time is at least displayed correctly, but Google Calendar still interprets it as CEST instead of CET.

Interesting to note is that even the external generator got the timezone wrong. If I compare with ICS files sent by Microsoft Teams for example, they do seem to get it right... I haven't got the time to figure out where the exact differences are though...

It's something I'll definitely get into at a later date. It would be great if this repo would allow a bit more customization. Maybe something like a manual mode, wherein most lines can be set manually? I'm just thinking out loud - it might defeat the purpose.

Thanks for your expert views and advice on the timezone issues, I appreciate it.
